//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HAFoodWeb.Cart
{
    public partial class CartItem
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl wrap;

        protected global::System.Web.UI.WebControls.CheckBox chkSelect;

        protected global::System.Web.UI.HtmlControls.HtmlImage imgProduct;

        protected global::System.Web.UI.WebControls.Literal litProductName;

        protected global::System.Web.UI.WebControls.Literal litVariantName;

        protected global::System.Web.UI.WebControls.Literal litPrice;

        protected global::System.Web.UI.WebControls.Literal litQty;

        protected global::System.Web.UI.WebControls.Literal litTotal;
    }
}
